In [11]:
import pandas as pd

structure_data = pd.read_csv('./train.csv')
structure_data

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [12]:
structure_data['label'].value_counts()

label
1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: count, dtype: int64

In [13]:
structure_data_shuffled_df = structure_data.sample(n=len(structure_data), random_state=1)
structure_data_shuffled_df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
29633      1       0       0       0       0       0       0       0       0   
345        5       0       0       0       0       0       0       0       0   
36369      2       0       0       0       0       0       0       0       0   
16624      8       0       0       0       0       0       0       0       0   
14389      4       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
7813       7       0       0       0       0       0       0       0       0   
32511      1       0       0       0       0       0       0       0       0   
5192       2       0       0       0       0       0       0       0       0   
12172      1       0       0       0       0       0       0       0       0   
33003      1       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
29633       0  ...         0         0         0         0         0   
345         0  ...         0         0         0         0         0   
36369       0  ...         0         0         0         0         0   
16624       0  ...         0         0         0         0         0   
14389       0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
7813        0  ...         0         0         0         0         0   
32511       0  ...         0         0         0         0         0   
5192        0  ...         0         0         0         0         0   
12172       0  ...         0         0         0         0         0   
33003       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
29633         0         0         0         0         0  
345           0         0         0         0         0  
36369         0         0         0         0         0  
16624         0         0         0         0         0  
14389         0         0         0         0         0  
...         ...       ...       ...       ...       ...  
7813          0         0         0         0         0  
32511         0         0         0         0         0  
5192          0         0         0         0         0  
12172         0         0         0         0         0  
33003         0         0         0         0         0  

[42000 rows x 785 columns]

In [14]:
pd.get_dummies(structure_data_shuffled_df['label']).head()

0      1      2      3      4      5      6      7      8      9
29633  False   True  False  False  False  False  False  False  False  False
345    False  False  False  False  False   True  False  False  False  False
36369  False  False   True  False  False  False  False  False  False  False
16624  False  False  False  False  False  False  False  False   True  False
14389  False  False  False  False   True  False  False  False  False  False

In [15]:
# get the data without the result
structure_data_shuffled = structure_data_shuffled_df.to_numpy()
structure_data_x_data = (structure_data_shuffled_df.drop(['label'], axis=1)).to_numpy()
structure_data_y_data = (structure_data_shuffled_df['label']).to_numpy()


In [16]:
#split the data into test, trin and validation data
X_train, y_train = structure_data_x_data[:30000], structure_data_y_data[:30000] 
X_val, y_val = structure_data_x_data[30000:], structure_data_y_data[30000:] 
columns_count = len(X_train[0])

X_train.shape, y_train.shape, X_val.shape, y_val.shape , type(X_train)

((30000, 784), (30000,), (12000, 784), (12000,), numpy.ndarray)

In [17]:
X_train[:20, 456:466]

array([[  0,   0,  19, 223, 253, 253, 179,  18,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 122, 254],
       [ 13, 109, 211, 124,  88, 213, 253, 226,  28,   0],
       [  0,   0,  10, 163, 252, 253, 253, 254, 253, 252],
       [  0,   0,   0,   0,  40, 116, 212, 254, 254, 246],
       [  0,   0,   0,   0,   0,   0,   0, 158, 255, 114],
       [252, 252, 112,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  37,   0,   0,   0,   0,  44, 243, 254, 254],
       [254, 254, 254, 254, 254, 254, 254, 254, 254, 146],
       [  0,  51, 236, 221,  28,   0,   0,  89, 254, 193],
       [ 73,   0,   0,   0,   0,   0,   0,  36, 156, 253],
       [  0,   0,   0,   0,   0,   0,  39, 224, 253, 130],
       [  0,   0,  20, 209, 253, 250, 246, 248, 253, 253],
       [  0,   0, 160, 248, 117,   2,   0,   0,   0,   0],
       [  0,  45, 243, 254, 254, 254, 175,  52, 205, 140],
       [  0, 198, 254, 255, 254, 254, 255, 252, 247, 246],
       [ 21, 145, 247, 251, 143,  24,   4,  79, 244, 243

In [18]:
# preprocessing with standard deviation to normalise data
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as pyplot
scaler = StandardScaler().fit(X_train)

def preprocessor(X):
  A = np.copy(X)
  A = scaler.transform(A)
  return A

# X_train = preprocessor(X_train)
X_train, X_val = preprocessor(X_train), preprocessor(X_val)

X_train[:20, 456:466]

array([[-0.65792156, -0.74245082, -0.61010337,  1.2474939 ,  1.38348961,
         1.2175014 ,  0.47423851, -0.97750535, -1.07436415, -0.99771844],
       [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.91701161,
        -1.02103571, -1.11523103, -1.1391554 ,  0.01280423,  1.28517005],
       [-0.52874595,  0.29221447,  1.19558356,  0.32516411, -0.11683727,
         0.86358249,  1.13133765,  0.89045081, -0.82485009, -0.99771844],
       [-0.65792156, -0.74245082, -0.69474494,  0.68850615,  1.37439672,
         1.2175014 ,  1.13133765,  1.14190645,  1.18017355,  1.26719455],
       [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.55329601,
         0.00532913,  0.76726921,  1.14190645,  1.18908477,  1.21326805],
       [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.91701161,
        -1.02103571, -1.11523103,  0.27977283,  1.19799599,  0.02688506],
       [ 1.84609811,  1.6496194 ,  0.26452624, -0.83007725, -0.91701161,
        -1.02103571, -1.11523103, -1.1391554 

In [19]:
X_train.shape, X_val.shape,X_train[:20, 456:466]

((30000, 784),
 (12000, 784),
 array([[-0.65792156, -0.74245082, -0.61010337,  1.2474939 ,  1.38348961,
          1.2175014 ,  0.47423851, -0.97750535, -1.07436415, -0.99771844],
        [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.91701161,
         -1.02103571, -1.11523103, -1.1391554 ,  0.01280423,  1.28517005],
        [-0.52874595,  0.29221447,  1.19558356,  0.32516411, -0.11683727,
          0.86358249,  1.13133765,  0.89045081, -0.82485009, -0.99771844],
        [-0.65792156, -0.74245082, -0.69474494,  0.68850615,  1.37439672,
          1.2175014 ,  1.13133765,  1.14190645,  1.18017355,  1.26719455],
        [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.55329601,
          0.00532913,  0.76726921,  1.14190645,  1.18908477,  1.21326805],
        [-0.65792156, -0.74245082, -0.78879114, -0.83007725, -0.91701161,
         -1.02103571, -1.11523103,  0.27977283,  1.19799599,  0.02688506],
        [ 1.84609811,  1.6496194 ,  0.26452624, -0.83007725, -0.91701161,
  

In [62]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import root_mean_squared_error as rmse

#create a new array that contains every columns in xdata, ydata, and pred
def merge_data(X_data, Y_data, Y_data_prediction):
    index =0
    result = []
    l_rows_count, l_columns_count = X_data.shape
    for element in Y_data:
        new_data =[]
        for i in range(l_columns_count):
            new_data.append( X_data[index, i])
        new_data.append('ans=')
        new_data.append(Y_data[index])
        new_data.append('pred=')
        new_data.append(Y_data_prediction[index])
        result.append(new_data)
        index+=1
    return result

def get_accuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size

def get_predictions(A2):
    return np.argmax(A2, 0)

def visualise_accuracy(X_train, X_val, y_train_onehot, y_val_onehot, y_train_pred, y_val_pred):
    #visualisation
    X_visual=X_val
    Y_visual=y_val
    Y_visual_pred =y_val_pred
    
    print(get_accuracy(y_val_pred, y_val_onehot))
    print(get_accuracy(y_train_onehot, y_train_pred))
    print(y_val_pred[40], y_val_onehot[40])
    print(y_val_pred[68], y_val_onehot[68])
    print(y_train_pred[40], y_train_onehot[40])
    
    # pyplot.scatter(X_visual[:20, 456], Y_visual[:20], c="red")
    # pyplot.scatter(X_visual[:20, 456], Y_visual_pred[:20], c="blue")
    # lsit = merge_data(X_visual[:20, 463:466],Y_visual[:20], Y_visual_pred[:20])
    # print(pd.DataFrame(lsit))
    # print("\nRMSE:", 'train:', rmse(y_train_pred, y_train), ', valid:', rmse(y_val_pred, y_val))


def visualise(X_train, X_val, y_val, y_train_pred, y_val_pred):
    #visualisation
    X_visual=X_val
    Y_visual=y_val
    Y_visual_pred =y_val_pred
    
    pred = get_predictions(y_val_pred)
    print(get_accuracy(y_val_pred, Y_visual))
    print(get_accuracy(y_val_pred, Y_visual))
    print(y_val_pred[40], Y_visual[40])
    print(y_val_pred[68], Y_visual[68])
    print(y_train_pred[40], Y_visual[40])
    
    pyplot.scatter(X_visual[:20, 456], Y_visual[:20], c="red")
    pyplot.scatter(X_visual[:20, 456], Y_visual_pred[:20], c="blue")
    lsit = merge_data(X_visual[:20, 463:466],Y_visual[:20], Y_visual_pred[:20])
    print(pd.DataFrame(lsit))
    print("\nRMSE:", 'train:', rmse(y_train_pred, y_train), ', valid:', rmse(y_val_pred, y_val))

def onehot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    # one_hot_Y = one_hot_Y.T
    return one_hot_Y


In [22]:
y_train_onehot = onehot(y_train)
y_val_onehot = onehot(y_val)

pd.DataFrame(X_train).head()

0    1    2    3    4    5    6    7    8    9    ...       774       775  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.035284 -0.026531   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.035284 -0.026531   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.035284 -0.026531   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.035284 -0.026531   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.035284 -0.026531   

        776       777       778       779  780  781  782  783  
0 -0.019013 -0.013364 -0.010107 -0.008161  0.0  0.0  0.0  0.0  
1 -0.019013 -0.013364 -0.010107 -0.008161  0.0  0.0  0.0  0.0  
2 -0.019013 -0.013364 -0.010107 -0.008161  0.0  0.0  0.0  0.0  
3 -0.019013 -0.013364 -0.010107 -0.008161  0.0  0.0  0.0  0.0  
4 -0.019013 -0.013364 -0.010107 -0.008161  0.0  0.0  0.0  0.0  

[5 rows x 784 columns]

In [ ]:
pd.DataFrame(X_train[:10, 456:466]).hist()

In [ ]:
(pd.DataFrame(X_train[0])).plot()

In [ ]:
X_train.shape, y_train.shape

In [ ]:
# try to train with different training models
from sklearn.linear_model import RidgeClassifier

lm = RidgeClassifier().fit(X_train, y_train)
#prediction
y_train_pred=lm.predict(X_train)
y_val_pred=lm.predict(X_val)

#visualisation
visualise(X_train, X_val, y_val, y_train_pred, y_val_pred)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10).fit(X_train, y_train)
#prediction
y_train_pred=knn.predict(X_train)
y_val_pred=knn.predict(X_val)

#visualisation
visualise(X_train, X_val, y_val, y_train_pred, y_val_pred)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfr = RandomForestClassifier(max_depth=10, n_estimators=1000).fit(X_train, y_train)
#prediction
y_train_pred=rfr.predict(X_train)
y_val_pred=rfr.predict(X_val)

#visualisation
visualise(X_train, X_val, y_val, y_train_pred, y_val_pred)


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gbr = GradientBoostingClassifier(n_estimators=10, learning_rate=0.1).fit(X_train, y_train)
#prediction
y_train_pred=gbr.predict(X_train)
y_val_pred=gbr.predict(X_val)


#visualisation
visualise(X_train, X_val, y_val, y_train_pred, y_val_pred)


In [66]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

simple_nn = Sequential()
simple_nn.add(InputLayer((columns_count,)))
simple_nn.add(Dense(784, 'relu'))
simple_nn.add(Dense(10, 'softmax'))


# print(y_train_onehot.shape, y_val_onehot.shape, y_val_onehot[1:4])
opt = Adam(learning_rate=.01)
cp = ModelCheckpoint('models/models-image/simple_nn.keras', save_best_only=True)
simple_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
simple_nn.fit(x=X_train, y=y_train_onehot, validation_data=(X_val, y_val_onehot), callbacks=[cp], epochs=4)


Epoch 1/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 19s 19ms/step - loss: 0.0883 - root_mean_squared_error: 0.2971 - val_loss: 0.1075 - val_root_mean_squared_error: 0.3279
Epoch 2/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 19s 20ms/step - loss: 0.1032 - root_mean_squared_error: 0.3212 - val_loss: 0.1000 - val_root_mean_squared_error: 0.3162
Epoch 3/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 17s 18ms/step - loss: 0.1022 - root_mean_squared_error: 0.3196 - val_loss: 0.0983 - val_root_mean_squared_error: 0.3135
Epoch 4/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 17s 18ms/step - loss: 0.0971 - root_mean_squared_error: 0.3116 - val_loss: 0.1000 - val_root_mean_squared_error: 0.3162
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [67]:
from tensorflow.keras.models import load_model

# simple_nn = load_model('models/models-image/simple_nn.keras')
#prediction
y_train_pred=simple_nn.predict(X_train)
y_val_pred=simple_nn.predict(X_val)

#visualisation
visualise_accuracy(X_train, X_val, y_train_onehot, y_val_onehot, y_train_pred, y_val_pred) 

938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
0.897475
0.8965533333333333
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [76]:
medium_nn = Sequential()
medium_nn.add(InputLayer((columns_count,)))
medium_nn.add(Dense(784, 'relu')) 
medium_nn.add(Dense(392, 'relu')) 
medium_nn.add(Dense(64, 'relu')) 
medium_nn.add(Dense(32, 'linear')) 
medium_nn.add(Dense(10, 'softmax'))

opt = Adam(learning_rate=.04)
cp = ModelCheckpoint('models/models-image/medium_nn.keras', save_best_only=True)
medium_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
medium_nn.fit(x=X_train, y=y_train_onehot, validation_data=(X_val, y_val_onehot), callbacks=[cp], epochs=4)

Epoch 1/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 26s 25ms/step - loss: 0.1814 - root_mean_squared_error: 0.4259 - val_loss: 0.1815 - val_root_mean_squared_error: 0.4260
Epoch 2/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 27s 29ms/step - loss: 0.1820 - root_mean_squared_error: 0.4266 - val_loss: 0.1815 - val_root_mean_squared_error: 0.4260
Epoch 3/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 26s 27ms/step - loss: 0.1814 - root_mean_squared_error: 0.4259 - val_loss: 0.1815 - val_root_mean_squared_error: 0.4260
Epoch 4/4
938/938 ━━━━━━━━━━━━━━━━━━━━ 27s 29ms/step - loss: 0.1820 - root_mean_squared_error: 0.4267 - val_loss: 0.1815 - val_root_mean_squared_error: 0.4260


In [77]:
# medium_nn = load_model('models/models-image/medium_nn.keras')
#prediction
y_train_pred=medium_nn.predict(X_train)
y_val_pred=medium_nn.predict(X_val)

#visualisation
visualise_accuracy(X_train, X_val, y_train_onehot, y_val_onehot, y_train_pred, y_val_pred) 

938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
0.8185
0.8179
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [79]:
large_nn = Sequential()
large_nn.add(InputLayer((columns_count,)))
large_nn.add(Dense(784, 'relu'))
large_nn.add(Dense(256, 'relu'))
large_nn.add(Dense(128, 'relu'))
large_nn.add(Dense(64, 'relu'))
large_nn.add(Dense(32, 'relu'))
large_nn.add(Dense(10, 'softmax'))

opt = Adam(learning_rate=.1)
cp = ModelCheckpoint('models/models-image/large_nn.keras', save_best_only=True)
large_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
large_nn.fit(x=X_train, y=y_train_onehot, validation_data=(X_val, y_val_onehot), callbacks=[cp], epochs=100)

Epoch 1/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 27s 25ms/step - loss: 0.1798 - root_mean_squared_error: 0.4240 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 2/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 22s 24ms/step - loss: 0.1806 - root_mean_squared_error: 0.4249 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 3/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 31s 33ms/step - loss: 0.1801 - root_mean_squared_error: 0.4244 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 4/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 33s 24ms/step - loss: 0.1804 - root_mean_squared_error: 0.4247 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 5/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 22s 23ms/step - loss: 0.1795 - root_mean_squared_error: 0.4236 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 6/100
938/938 ━━━━━━━━━━━━━━━━━━━━ 21s 22ms/step - loss: 0.1798 - root_mean_squared_error: 0.4240 - val_loss: 0.1809 - val_root_mean_squared_error: 0.4253
Epoch 7/100
938/938 ━━━━━━━━━━━━━━

In [80]:
large_nn = load_model('models/models-image/large_nn.keras')
#prediction
y_train_pred=large_nn.predict(X_train)
y_val_pred=large_nn.predict(X_val)

#visualisation
visualise_accuracy(X_train, X_val, y_train_onehot, y_val_onehot, y_train_pred, y_val_pred) 

938/938 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step
375/375 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step
0.8190833333333334
0.8199466666666667
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [81]:
larger_nn = Sequential()
larger_nn.add(InputLayer((columns_count,)))
larger_nn.add(Dense(256, 'relu'))
larger_nn.add(Dense(128, 'relu'))
larger_nn.add(Dense(64, 'relu'))
larger_nn.add(Dense(32, 'relu'))
larger_nn.add(Dense(1, 'linear'))

opt = Adam(learning_rate=.1)
cp = ModelCheckpoint('models/models-image/larger_nn.keras', save_best_only=True)
larger_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
larger_nn.fit(x=X_train, y=y_train, validation_data=(X_val, y_val), callbacks=[cp], epochs=300)

Epoch 1/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 30s 21ms/step - loss: 81650.1172 - root_mean_squared_error: 216.5470 - val_loss: 8.3283 - val_root_mean_squared_error: 2.8859
Epoch 2/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 21s 21ms/step - loss: 30.5220 - root_mean_squared_error: 5.3661 - val_loss: 9.0546 - val_root_mean_squared_error: 3.0091
Epoch 3/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 21s 21ms/step - loss: 8.7954 - root_mean_squared_error: 2.9654 - val_loss: 8.2560 - val_root_mean_squared_error: 2.8733
Epoch 4/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 26s 25ms/step - loss: 8.2765 - root_mean_squared_error: 2.8768 - val_loss: 8.2552 - val_root_mean_squared_error: 2.8732
Epoch 5/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 46s 31ms/step - loss: 8.3913 - root_mean_squared_error: 2.8968 - val_loss: 8.2541 - val_root_mean_squared_error: 2.8730
Epoch 6/300
938/938 ━━━━━━━━━━━━━━━━━━━━ 32s 20ms/step - loss: 8.3918 - root_mean_squared_error: 2.8968 - val_loss: 8.2544 - val_root_mean_squared_error: 2.8731
Epoch 7/300
938/938 ━━━━━━━

In [82]:
larger_nn = load_model('models/models-image/large_nn.keras')
#prediction
y_train_pred=larger_nn.predict(X_train)
y_val_pred=larger_nn.predict(X_val)

#visualisation
visualise_accuracy(X_train, X_val, y_train_onehot, y_val_onehot, y_train_pred, y_val_pred) 

938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
0.8190833333333334
0.8199466666666667
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
